### ISSUE TITLE
Add StyleGAN to hubconf.py

### ISSUE THREAD

**Issue by EdwardRaff** [facebookresearch/pytorch_GAN_zoo#110]
Hi, thanks for making your code available through the PyTorch hub! Its been very useful for a lecture I'm writing about  GANs. I wanted to ask if StylGAN will be made available in the same manner, as the results are better and it makes the Colab notebooks much easier for students to run.

**Comment by Molugan** [comment]
Hello,
Sorry for the delay. StyleGAN is more or less a beta and I felt a bit uncomfortable adding it to the torchhub. Let me see if I still have a decent pre-trained model in stock.

**Comment by Molugan** [comment]
<img width="842" alt="image" src="https://user-images.githubusercontent.com/23697994/81952432-c4909000-9606-11ea-981f-e4d201c64c8e.png">
