### ISSUE TITLE
where does the input dimension changes in discriminator?

### ISSUE THREAD

**Issue by Yoonho-Na** [facebookresearch/pytorch_GAN_zoo#134]
I'm using PGGAN and I found out that
in the optimizeParameters function on base_GAN.py, the self.real_input shape changes right after it enters discriminator(before going through any layers).
the self.real_input had shape of [16, 3, 4, 4]
and I printed out the input x, in the discriminator forward function
It printed [4,3,4,4] .
why is that and where does it change the dimension?

**Comment by LiUzHiAn** [comment]
Did you use multi-GPUs to train?  Maybe 4 GPUs I guess?

**Comment by Yoonho-Na** [comment]
> Did you use multi-GPUs to train? Maybe 4 GPUs I guess?

Yes that was the problem.
