### ISSUE TITLE
Undefined name 'PPGANTrainer' in DCGAN_trainer.py

### ISSUE THREAD

**Issue by cclauss** [facebookresearch/pytorch_GAN_zoo#53]
[flake8](http://flake8.pycqa.org) testing of https://github.com/facebookresearch/pytorch_GAN_zoo on Python 3.7.1

$ __flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics__
```
./models/trainer/DCGAN_trainer.py:19:16: F821 undefined name 'PPGANTrainer'
        return PPGANTrainer._defaultConfig
               ^
1     F821 undefined name 'PPGANTrainer'
1
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. These 5 are different from most other flake8 issues which are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

**Comment by Molugan** [comment]
https://github.com/facebookresearch/pytorch_GAN_zoo/pull/55
