### ISSUE TITLE
Using multiple GPUs for progressive GAN

### ISSUE THREAD

**Issue by Spandan-Madan** [facebookresearch/pytorch_GAN_zoo#57]
As the model can take a few days to train, it might be useful to add multiple GPU support. Is there any work on that?

If not, I can fork and create a pull request for a version with multiple GPUs.

Best,
Spandan

**Comment by Molugan** [comment]
Hi,

Sorry for the delay. There is already multiple GPU support: if you have a look at https://github.com/facebookresearch/pytorch_GAN_zoo/blob/d87a196fc382d6904180c6d9e241458bcb37ce22/models/base_GAN.py#L315 the baseGan model automatically load all GPUs available.

There isn't already a way to load a smaller amount of GPUs thought.

**Comment by Spandan-Madan** [comment]
@Molugan I'm sure you can just launch the script with a "CUDA_VISIBLE_DEVICES=0,1" to force it to only find GPU devices with IDs 0 and 1 if someone wants to use just those 2 GPUs.

Thanks,
Spandan

**Comment by albusdemens** [comment]
For posterity: ` CUDA_VISIBLE_DEVICES=0,1 python ...` didn't work, so instead I used the commands
```
export CUDA_VISIBLE_DEVICES=xx, yy
python train.py StyleGAN -c config.json
```
