### ISSUE TITLE
How to start training Progressive GAN from size 8x8 instead of 4x4

### ISSUE THREAD

**Issue by pratikm141** [facebookresearch/pytorch_GAN_zoo#75]
How to start training Progressive GAN from size 8x8 instead of 4x4?

**Comment by Molugan** [comment]
Hi,

Sorry for the delay. To start training from 8x8 resolution you have two options:

1) You can set the number of iteration for the scale 0 to 0 in the configuration file corresponding to your training.

Typically you would have a file like:

```
"pathDB": $PATH_TO_YOUR_DATASET,
  "config": {
    "maxIterAtScale": [
      0,
      120000,
      120000,
      120000
    ],
"alphaNJumps":[0,0,600, 600]
}
```

2) Modify the code and call ProgresssiveGANTrainer.addNewScales at the beginning of your training.
