### ISSUE TITLE
StyleGAN support

### ISSUE THREAD

**Issue by eitanrich** [facebookresearch/pytorch_GAN_zoo#77]
Is there an estimate for when StyleGAN will be added?

**Comment by lzhbrian** [comment]
same question here.

**Comment by mkondela** [comment]
Same question as well, especially interested in a comparison to already existing implementations.

**Comment by Molugan** [comment]
Sorry for the delay:
There is a beta version of StyleGAN ongoing. But it still has some bugs. I will release it within a week or two.

**Comment by kondela** [comment]
@Molugan Is the pull request delayed by the release of [StyleGAN2 ](https://github.com/NVlabs/stylegan2) by any chance?

**Comment by Molugan** [comment]
PR incoming, you can start to work with the branch but I need to check that everything os ok.

https://github.com/facebookresearch/pytorch_GAN_zoo/pull/95
