### ISSUE TITLE
How do I make the size of the input picture

### ISSUE THREAD

**Issue by Johnson-yue** [facebookresearch/pytorch_GAN_zoo#81]
I will train PGAN with my own dataset， but My data image size is 64x64 , So , how can I set image size in configuration ?

**Comment by Molugan** [comment]
You don't set the image size as an input, however you can choose the number of scales to work with.
THe scales are numeroted as follow:
scale 0: 4x4
scale 1: 8x8
etc..

So 64x64 is scale 4. To work with images of this size you must only set 5 values in the maxIterAtScale parameter of your configuratio file

ex:
config["config"]["maxIterAtScale"] = [48000, 96000, 96000, 96000,96000]
scale 0: 48000 iterations, scale 1 96000,.. scale 4 96000

**Comment by ivder** [comment]
@Molugan Hi how do you choose the `maxIterAtScale` value? How did you set the 48000, 96000, 120000, etc ?
