### ISSUE TITLE
I can't using GDPP config train any model

### ISSUE THREAD

**Issue by Johnson-yue** [facebookresearch/pytorch_GAN_zoo#83]
Hi, I will train PGAN with cifar10 dataset  and GDPP using this command:

> python datasets.py cifar10 $PATH_TO_CIFAR10 -o $OUTPUT_DATASET
> python train.py PGAN -c config_cifar10.json --restart -n cifar10 --GDPP True

But, I got error 
`RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time`

When I check the code : 
[backward lossGFake](https://github.com/facebookresearch/pytorch_GAN_zoo/blob/1a0c76496792d4aa0904eb0afc80ea42c5f73b08/models/base_GAN.py#L257) the compute graph has been released. So when [backward GDPP loss](https://github.com/facebookresearch/pytorch_GAN_zoo/blob/1a0c76496792d4aa0904eb0afc80ea42c5f73b08/models/base_GAN.py#L261) there is not compute graph or any node will be computed.
and Occur this error!!

**Comment by leiluoray1** [comment]
I had the same error.

**Comment by Johnson-yue** [comment]
The original paper said 

> loss_g = loss_adv + loss_gdpp

But in this implement,   first backward only loss_adv and then backward loss_gdpp
Is right?

**Comment by Molugan** [comment]
Doing the backward in different places doesn't change the loss.

**Comment by Molugan** [comment]
https://github.com/facebookresearch/pytorch_GAN_zoo/pull/85
