### ISSUE TITLE
What is the appropriate version of pytorch?

### ISSUE THREAD

**Issue by yangzhikai** [facebookresearch/pytorch_GAN_zoo#86]
pytorch0.3 or pytorch0.4 or pytorch1.0?

**Comment by Molugan** [comment]
Hi,

You will need pytorch 1.0 or higher to use this repo.

**Comment by yangzhikai** [comment]
@Molugan Have you try it on pytorch4.1?  I would like to try it on 0.41, and I well tell us the results.
