### ISSUE TITLE
GDPPLoss can become NaN

### ISSUE THREAD

**Issue by Quasimondo** [facebookresearch/pytorch_GAN_zoo#89]
It's probably a rare edge case, but I noticed that in the normalization function a division by zero can occur if minV == maxV in which case the returned loss will become NaN and probably poison the rest of the model even if it just happens once.

So I'd propose to add a safeguard (I tried adding a small epsilon first, but that lead to wrong results)

```
def normalize_min_max(eigVals):
        minV, maxV = torch.min(eigVals), torch.max(eigVals)
        if minV == maxV:
            return eigVals
        return (eigVals - minV) / (maxV - minV)
 
```

**Comment by Molugan** [comment]
Sorry for the delay. Good point indeed I should make a PR.
