### ISSUE TITLE
How to generate more images?

### ISSUE THREAD

**Issue by ivder** [facebookresearch/pytorch_GAN_zoo#91]
Thanks for the great work. I'm using Cifar-10 dataset and I notice that it will generate 16 images (8x8) like this : 
![image](https://user-images.githubusercontent.com/32887298/70006783-b814ff80-15b1-11ea-86ff-842cb1c339de.png)

How to generate more than 8x8 images? Do I need to to modify the source code or the option is available in the config file?

**Comment by Molugan** [comment]
Hi,

Right now the number of images is hardcoded here https://github.com/facebookresearch/pytorch_GAN_zoo/blob/master/models/trainer/gan_trainer.py#L118

Just beware that if you restart a training model it will reuse the old visualization vector. To avoid that, delete *_refVectors.pt before restarting.
