### ISSUE TITLE
How to split generated image?

### ISSUE THREAD

**Issue by ivder** [facebookresearch/pytorch_GAN_zoo#94]
After evaluating the model using
`python eval.py visualization -n $modelName -m $modelType`
it will generate a big image consists of `nImages = (256 // 2**(max(scale - 2, 3))) * 8` , for example 8x32 = 256 images. 

How to split / save the small images separately instead of the combined big image? 1 jpg for 1 generated image

**Comment by Molugan** [comment]
Hi,

To do that you can add the option --save_dataset $PATH_OUTPUT to your script: it will export 1 image per jpg. The default number of images to export is 1000 you might want to change that.

**Comment by ivder** [comment]
@Molugan thx for the confirmation. The `--save_dataset` flag usefulness is a little bit unclear in the Readme file. Would be lot better if you add a sample image of the command's result. Thank you by the way
